export const destinations = [
  {
    id: 1,
    name: 'Tbilisi',
    region: 'Capital City',
    tagline: 'Where East Meets West',
    description:
      'A city of ancient sulfur baths, colourful balconied houses, and a thriving arts scene set in a dramatic river gorge.',
    image: 'https://picsum.photos/seed/tbilisi-old-town/800/560',
    heroImage: 'https://picsum.photos/seed/tbilisi-hero/1600/900',
    highlights: ['Old Town', 'Narikala Fortress', 'Sulfur Baths', 'Rustaveli Ave'],
    duration: '2–3 days',
    bestTime: 'Apr – Jun, Sep – Oct',
    rating: 4.9,
    reviews: 312,
    featured: true,
  },
  {
    id: 2,
    name: 'Kazbegi',
    region: 'Greater Caucasus',
    tagline: 'Roof of the Caucasus',
    description:
      'Majestic alpine scenery crowned by the legendary Gergeti Trinity Church perched above dramatic Caucasian peaks.',
    image: 'https://picsum.photos/seed/kazbegi-mountains/800/560',
    heroImage: 'https://picsum.photos/seed/kazbegi-hero/1600/900',
    highlights: ['Gergeti Trinity Church', 'Mt. Kazbek', 'Truso Valley', 'Sno Valley'],
    duration: '2–4 days',
    bestTime: 'Jun – Sep',
    rating: 5.0,
    reviews: 248,
    featured: true,
  },
  {
    id: 3,
    name: 'Batumi',
    region: 'Adjara',
    tagline: 'Pearl of the Black Sea',
    description:
      'A vibrant resort city blending belle-époque architecture with modern skyscrapers along a lush subtropical coast.',
    image: 'https://picsum.photos/seed/batumi-coast/800/560',
    heroImage: 'https://picsum.photos/seed/batumi-hero/1600/900',
    highlights: ['Boulevard', 'Botanical Garden', 'Old Town', 'Alphabet Tower'],
    duration: '2–3 days',
    bestTime: 'Jun – Sep',
    rating: 4.7,
    reviews: 196,
    featured: true,
  },
  {
    id: 4,
    name: 'Kakheti',
    region: 'Wine Country',
    tagline: 'Cradle of Wine',
    description:
      "Georgia's premier wine region, home to 8,000 years of winemaking tradition, ancient monasteries, and rolling vineyards.",
    image: 'https://picsum.photos/seed/kakheti-vineyard/800/560',
    heroImage: 'https://picsum.photos/seed/kakheti-hero/1600/900',
    highlights: ['Sighnaghi', 'Bodbe Monastery', 'Wine Caves', 'Alazani Valley'],
    duration: '2–3 days',
    bestTime: 'Sep – Oct (harvest)',
    rating: 4.8,
    reviews: 187,
    featured: false,
  },
  {
    id: 5,
    name: 'Svaneti',
    region: 'Upper Svaneti',
    tagline: 'Land of the Towers',
    description:
      'A UNESCO World Heritage landscape of medieval stone towers, glaciers, and villages untouched by time.',
    image: 'https://picsum.photos/seed/svaneti-towers/800/560',
    heroImage: 'https://picsum.photos/seed/svaneti-hero/1600/900',
    highlights: ['Mestia', 'Ushguli Village', 'Koruldi Lakes', 'Glacier Hiking'],
    duration: '3–5 days',
    bestTime: 'Jun – Sep',
    rating: 4.9,
    reviews: 143,
    featured: false,
  },
  {
    id: 6,
    name: 'Mtskheta',
    region: 'Kartli',
    tagline: 'Ancient Capital',
    description:
      'The spiritual heart of Georgia, where two rivers meet beneath centuries-old cathedrals and monasteries.',
    image: 'https://picsum.photos/seed/mtskheta-cathedral/800/560',
    heroImage: 'https://picsum.photos/seed/mtskheta-hero/1600/900',
    highlights: ['Svetitskhoveli Cathedral', 'Jvari Monastery', 'Shiomgvime', 'Samtavro'],
    duration: '1 day',
    bestTime: 'Year-round',
    rating: 4.8,
    reviews: 289,
    featured: false,
  },
]
