export const tours = [
  {
    id: 1,
    title: 'Ultimate Georgia Discovery',
    slug: 'ultimate-georgia-discovery',
    category: 'Signature',
    badge: 'Best Seller',
    description:
      'Our flagship 10-day journey through Georgia\'s most iconic landscapes, cities, and cultural treasures.',
    image: 'https://picsum.photos/seed/tour-discovery/800/560',
    duration: '10 days',
    groupSize: '2–12',
    difficulty: 'Moderate',
    price: 2890,
    originalPrice: 3400,
    currency: 'USD',
    rating: 5.0,
    reviews: 97,
    includes: ['All accommodation', 'Private transport', 'Expert guide', 'Most meals'],
    destinations: ['Tbilisi', 'Mtskheta', 'Kazbegi', 'Kakheti', 'Batumi'],
    featured: true,
  },
  {
    id: 2,
    title: 'Caucasus Mountain Trek',
    slug: 'caucasus-mountain-trek',
    category: 'Adventure',
    badge: 'New',
    description:
      'A thrilling high-altitude adventure through Kazbegi and Svaneti, with glacier hikes and mountain village stays.',
    image: 'https://picsum.photos/seed/tour-mountain/800/560',
    duration: '7 days',
    groupSize: '4–10',
    difficulty: 'Challenging',
    price: 1950,
    originalPrice: null,
    currency: 'USD',
    rating: 4.9,
    reviews: 64,
    includes: ['Mountain lodge stays', 'Trekking gear', 'Expert guide', 'All meals'],
    destinations: ['Kazbegi', 'Svaneti', 'Mestia'],
    featured: true,
  },
  {
    id: 3,
    title: 'Wine & Culture Journey',
    slug: 'wine-culture-journey',
    category: 'Culinary',
    badge: 'Popular',
    description:
      'Immerse yourself in 8,000 years of winemaking tradition across Kakheti\'s amber valleys.',
    image: 'https://picsum.photos/seed/tour-wine/800/560',
    duration: '5 days',
    groupSize: '2–8',
    difficulty: 'Easy',
    price: 1290,
    originalPrice: 1490,
    currency: 'USD',
    rating: 4.8,
    reviews: 112,
    includes: ['Boutique hotel', 'Wine tastings', 'Cellar tours', 'Georgian feasts'],
    destinations: ['Kakheti', 'Sighnaghi', 'Telavi'],
    featured: true,
  },
  {
    id: 4,
    title: 'Tbilisi Deep Dive',
    slug: 'tbilisi-deep-dive',
    category: 'Cultural',
    badge: null,
    description:
      'Explore the layered history, art, and gastronomy of Georgia\'s extraordinary capital with a local insider.',
    image: 'https://picsum.photos/seed/tour-tbilisi/800/560',
    duration: '3 days',
    groupSize: '2–6',
    difficulty: 'Easy',
    price: 780,
    originalPrice: null,
    currency: 'USD',
    rating: 4.9,
    reviews: 83,
    includes: ['Boutique hotel', 'City tours', 'Food walks', 'Museum entry'],
    destinations: ['Tbilisi'],
    featured: false,
  },
  {
    id: 5,
    title: 'Black Sea & Batumi Escape',
    slug: 'black-sea-batumi-escape',
    category: 'Leisure',
    badge: null,
    description:
      "A sophisticated coastal retreat combining Batumi's vibrant city life with Adjaran nature excursions.",
    image: 'https://picsum.photos/seed/tour-batumi/800/560',
    duration: '4 days',
    groupSize: '2–10',
    difficulty: 'Easy',
    price: 990,
    originalPrice: null,
    currency: 'USD',
    rating: 4.7,
    reviews: 51,
    includes: ['Sea-view hotel', 'City tour', 'Botanical Garden', 'Speed boat trip'],
    destinations: ['Batumi', 'Gonio', 'Mtirala Park'],
    featured: false,
  },
  {
    id: 6,
    title: 'Svaneti & UNESCO Heritage',
    slug: 'svaneti-heritage',
    category: 'Adventure',
    badge: null,
    description:
      "Journey to one of Europe's most remote and magnificent highland regions, home to ancient defensive towers.",
    image: 'https://picsum.photos/seed/tour-svaneti/800/560',
    duration: '6 days',
    groupSize: '4–12',
    difficulty: 'Moderate',
    price: 1650,
    originalPrice: null,
    currency: 'USD',
    rating: 4.9,
    reviews: 38,
    includes: ['Guesthouse stays', 'Local guide', '4x4 transfers', 'Most meals'],
    destinations: ['Svaneti', 'Mestia', 'Ushguli'],
    featured: false,
  },
]

export const experiences = [
  {
    id: 1,
    title: 'Wine Tasting',
    description: 'Discover 8,000 years of winemaking tradition in ancient qvevri cellars.',
    icon: '🍷',
    color: '#722F37',
  },
  {
    id: 2,
    title: 'Mountain Hiking',
    description: 'Trek through dramatic Caucasian peaks and glacial valleys.',
    icon: '🏔️',
    color: '#4A6741',
  },
  {
    id: 3,
    title: 'Historic Sites',
    description: 'Walk through 3,000 years of history at UNESCO World Heritage sites.',
    icon: '🏛️',
    color: '#8B6914',
  },
  {
    id: 4,
    title: 'Culinary Tours',
    description: 'Savour khinkali, khachapuri, and regional delicacies at their source.',
    icon: '🍽️',
    color: '#C0392B',
  },
  {
    id: 5,
    title: 'Village Life',
    description: 'Immerse in authentic hospitality with traditional Georgian families.',
    icon: '🏡',
    color: '#7D5A50',
  },
  {
    id: 6,
    title: 'Cultural Shows',
    description: 'Experience polyphonic singing, traditional dance, and folk art.',
    icon: '🎭',
    color: '#9B59B6',
  },
]
